### ISSUE TITLE
Load secretjs from cdn

### ISSUE THREAD

**Issue by darwinzer0** [scrtlabs/secret.js#144]
This is a feature request. secret.js adds a lot to bundle file size when imported (over 1 MB). It would be great if you could include min.js release versions to the repo, so secret.js can be loaded from a CDN instead of bundling and downloading from every website that uses it. https://www.jsdelivr.com/?docs=gh . Thanks.

**Comment by dakom** [comment]
+1 for this - in addition to the size, this would also make it much easier for Rust/WASM frontend apps that use trunk.rs or similar, without a JS bundle step, to just include it in a <script> tag.

**Comment by dakom** [comment]
I see, the only issue is size, the bundle itself is available on CDN e.g. https://www.unpkg.com/secretjs@1.8.1/dist/browser.js

**Comment by Cashmaney** [comment]
Yeah, browser.js is already minified. The size comes from a lot of the dependencies/protobufs not getting efficiently shaken since we're building the library for compatibility over efficiency. 

If you want to give it a spin, I compiled a couple of more efficient versions which may or may not work:

https://engfilestorage.blob.core.windows.net/filestorage/browser.js - full secret.js
https://engfilestorage.blob.core.windows.net/filestorage/light.js - contains a SecretNetworkClient with only the bank, compute and auth modules
